# Generated by Django 5.2.7 on 2025-10-09 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("opening_hours", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "primary_series_doses",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("recurrence_interval_years", models.FloatField(blank=True, null=True)),
                ("booster_interval_years", models.FloatField(blank=True, null=True)),
                ("price_per_dose", models.DecimalField(decimal_places=2, max_digits=8)),
                ("side_effects", models.JSONField(blank=True, default=list)),
                ("administration_route", models.CharField(default="IM", max_length=10)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("age_min", models.FloatField(blank=True, null=True)),
                ("age_max", models.FloatField(blank=True, null=True)),
                ("contraindications", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.branch"
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vaccine"
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="Dose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_administered", models.DateField()),
                ("dose_number", models.PositiveSmallIntegerField()),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.vaccine"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_administered"],
                "unique_together": {("vaccine", "user", "dose_number")},
            },
        ),
    ]
