# Generated by Django 5.2.7 on 2025-10-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
