# Generated by Django 5.2.7 on 2025-10-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_branch_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="status",
        ),
    ]
