# Generated by Django 5.2.7 on 2025-11-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dose",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doses",
                to="core.appointment",
            ),
        ),
    ]
